AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  NodeJS 20.x
  Sample SAM Template for puppeter docker lambda

Globals:
  Function:
    Timeout: 120
    MemorySize: 2048

Resources:
  PuppeteerPdfFunction:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: "puppeteer-pdf-function"
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        Puppeteer:
          Type: Api 
          Properties:
            Path: /generatepdf
            Method: get
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./src

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  PuppeteerApi:
    Description: "API Gateway endpoint URL for Prod stage for Puppeteer function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/generatepdf/"
  PuppeteerPdfFunction:
    Description: "Selenium Lambda Function ARN"
    Value: !GetAtt PuppeteerPdfFunction.Arn